### ISSUE TITLE
id在哪里？搞不明白呀555

### ISSUE THREAD

**Issue by nokaka** [oxguy/openwrt-ddns-name-com#1]

**Comment by jibenfa** [comment]
要发个指令给后台的。 curl -u 'YOUR_USER_NAME:YOUR_API_TOKEN' 'https://api.name.com/v4/domains/example.com/records' -X POST --data '{"host":"www","type":"A","answer":"YOUR_IP","ttl":300}'   返回的数据里面就有id

**Comment by nokaka** [comment]
感谢感谢，可能昨天哪里没写对，今天拿到id了。
